[build]
  command = "yarn build"
  functions = "./functions"
  publish = "build"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = '/api/*'
  to = 'https://lucid-sammet-7f2164.netlify.com/:splat'
  status = 200
  
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"